name: ExamplePlugin
version: 1.0.0
main: com.example.plugin.ExamplePlugin
api-version: '1.20'
description: Example plugin demonstrating RabbitMQ library usage
author: 1nstagram

commands:
  announce:
    description: Send an announcement to all servers
    usage: /<command> <message>
    permission: example.announce
  rabbitmq:
    description: Check RabbitMQ connection status
    usage: /<command> status
    permission: example.admin

permissions:
  example.announce:
    description: Allows sending announcements
    default: op
  example.admin:
    description: Admin commands
    default: op
